export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_COMMENTS_BYID = 'GET_COMMENTS_BYID';
export const DELETE_COMMENTS = 'DELETE_COMMENTS';
export const CREATE_COMMENTS = 'CREATE_COMMENTS';
